### ISSUE TITLE
Usage with other plugins

### ISSUE THREAD

**Issue by wonnado** [istresearch/kibana-object-format#11]
Hi, thanks for your plugin! I tried to use your plugin with [Own Home](https://github.com/wtakase/kibana-own-home), but I got an error 
`Uncaught Error: [$injector:unpr] Unknown provider: confirmModalPromiseProvider <- confirmModalPromise <- indexPatterns <- courier
http://errors.angularjs.org/1.4.7/$injector/unpr?p0=confirmModalPromiseProvider%20%3C-%20confirmModalPromise%20%3C-%20indexPatterns%20%3C-%20courier` and don't have any idea what is the reason.
Maybe you can give me a piece of advice?
Thanks a lot!

**Comment by andrewkcarter** [comment]
@wonnado Thanks for the report. I've seen this with another plugin too, and I haven't been able to track the source of the issue yet.

**Comment by angeloudy** [comment]
I am having the same issue.
`Error: [$injector:unpr] Unknown provider: confirmModalPromiseProvider <- confirmModalPromise <- indexPatterns <- courier http://errors.angularjs.org/1.4.7/$injector/unpr?p0=confirmModalPromiseProvider%20%3C-%20confirmModalPromise%20%3C-%20indexPatterns%20%3C-%20courier (https://logs.ish.com.au/bundles/commons.bundle.js?v=14823:35)`

**Comment by andrewkcarter** [comment]
Feel free to submit a PR if you have a solution.
