### ISSUE TITLE
How to use with unknown property in object 

### ISSUE THREAD

**Issue by MatthD** [istresearch/kibana-object-format#12]
Hi!

I installed the plugin & it works but I would like to use it on unknown property name . I have those kind of objects:

"Guys": {
"Paul" : { age: 13, town : "Paris"},
"Pierre" : { age: 13, town : "NewYork"}
}

it's a sample eg I do not have this really ;) but it's to demonstrate that I do not know in advance the name of the main properties.
I just want to 
So I tried to put "*" as "Field (dot notation)" but this does not works.

Is it possible to do this or not ?

**Comment by andrewkcarter** [comment]
Hi @MatthD. That's not implemented. I can take it as a feature request, but I don't have a lot of time lately. If you wanted to provide a PR I would be happy to accept it. If you chose to go this route let me know so that we can align on the behavior expectations.
