### ISSUE TITLE
how can install this plugin

### ISSUE THREAD

**Issue by Marjani** [istresearch/kibana-object-format#19]
Hi
I'm sorry for simple question!
How can I add this plugin to Kibana?

**Comment by andrewkcarter** [comment]
From your kibana directory, run:
```
./bin/kibana-plugin install https://github.com/istresearch/kibana-object-format/releases/download/v0.1.2_kbn-5.6.7/kibana_object_format-0.1.2-kbn_6.2.1.zip
```
The URL comes from the *Assets* list of the [releases page](https://github.com/istresearch/kibana-object-format/releases). Pick one that matches your Kibana version. 

You can also follow [Kibana's documentation](https://www.elastic.co/guide/en/kibana/current/_installing_plugins.html).
