### ISSUE TITLE
Don't understand fieldMapperHack:fields

### ISSUE THREAD

**Issue by filippoleoncini** [istresearch/kibana-object-format#2]
I have an index pattern called "Luke". 

I have this json:
'
					"intents" : {
						"type" : "object",
						"properties" : {
							"intent" : {"type" : "string"},
							"confidence" : {"type" : "float"}
	                                    }
'
I don't uderstand what I have to do with the Advanced Setting "fieldMapperHack:fields". 

The .gif image doesn't show this step of configuration.

**Comment by filippoleoncini** [comment]
Here the mapping 
'
"mapping":{
	"default" : {
	"properties" :{
                             "intents" : {
						"type" : "object",
						"properties" : {
							"intent" : {"type" : "string"},
							"confidence" : {"type" : "float"}
						}
                                 }
                    }
} '

**Comment by andrewkcarter** [comment]
Try this as the value for `fieldMapperHack:fields`.
```
{
    "index_pattern":{
        "Luke":{
            "include":[
                "^intents$"
            ]
        }
    }
}
```
This means for the index pattern name `Luke`, you want to insert a row into the fields table for a field named `intents`.

I do need to provide some actual documentation for this. It's on my todo list. But in the meantime, please feel free to continue to ask your questions here.

**Comment by filippoleoncini** [comment]
Thank for your answer, but it doesn't work.

At this point I'll try to give you all my file:

- Mapping json

' { "mapping":{
	"default" : {
	"properties" :{

		{
			"id" : {"type" : "string"},
			"key" : {"type" : "string"},
			"value" : {
				"type" : "object",
				"properties" : {
					"rev" : {"type" : "string"}
				}
			},
			"doc" : {
				"type" : "object"
				"properties" : {
					"_id" : {"type", "string"},
					"_rev" : {"type" : "string"},
					"userID" : {"type" : "string"},
					"conversation_id" : {"type" : "string"},
					"input":{
						"type" : "object"
						"properties" : {
							"text" : {"type" : "string"}
						}
					},
					"output":{
						"type" : "object"
						"properties" : {
							"text" : {"type" : "string"}
						}
					},
					"node_visited" : {"type" : "string"},
					"intents" : {
						"type" : "object",
						"properties" : {
							"intent" : {"type" : "string"},
							"confidence" : {"type" : "float"}
						}
					},
					"entities" : {
						"type" : {"object"}
						"properties" :{
							"entity" : {"type" : "string"},
							"location" : {"type" : "string"},
							"value" : {"type" : "string"},
							"confidence" : {"type" : "string"}
							}
					},
					"timestamp" : {"type" : "date"}
			}
		}
		}
	}
	}
}	'

- My json data: 

' {
	"id" : "2a587d9fa1bdebeab7e3437e1438a570",
	"key" : "2a587d9fa1bdebeab7e3437e1438a570",
	"intents_new" : "",
	"value" : {
		"rev" : "1-6f932587e528af229af959867bdb0a43"
	},
	"doc" : {
		"_id" : "2a587d9fa1bdebeab7e3437e1438a570",
		"_rev" : "1-6f932587e528af229af959867bdb0a43",
		"timestamp" : "Mon, 15 May 2017 08:31:12 GMT",
		"APIresponse" : {
			"intents" : [{
					"intent" : "feedback-yes",
					"confidence" : 1
				}, {
					"intent" : "machineBusy",
					"confidence" : 0
				}, {
					"intent" : "faqGuidelinesPAAmount",
					"confidence" : 0
				}, {
					"intent" : "faqGuidelinesDisabilities",
					"confidence" : 0
				}, {
					"intent" : "feedback-no",
					"confidence" : 0
				}, {
					"intent" : "faqGuidelinesWhatsnew",
					"confidence" : 0
				}, {
					"intent" : "faqGuidelinesChildren",
					"confidence" : 0
				}, {
					"intent" : "faqGuidelinesPAvsFederal",
					"confidence" : 0
				}, {
					"intent" : "endExercise",
					"confidence" : 0
				}, {
					"intent" : "faqGuidelinesCommunities",
					"confidence" : 0
				}
			],
			"entities" : [],
			"input" : {
				"text" : "yes"
			},
			"output" : {
				"log_messages" : [],
				"text" : ["How much do you weight?"],
				"nodes_visited" : ["node_1_1492190797231", "node_2_1492191180727", "node_1_1492374340527", "profiling - question weight"]
			},
			"context" : {
				"conversation_id" : "24499b64-433a-46a1-ae7f-6cc5092517be",
				"system" : {
					"dialog_stack" : [{
							"dialog_node" : "profiling - question weight"
						}
					],
					"dialog_turn_counter" : 2,
					"dialog_request_counter" : 2,
					"_node_output_map" : {
						"NOTIFY STATUS" : [0],
						"node_3_1494542825768" : [0],
						"node_4_1493366149312" : [0],
						"profiling - question weight" : [0]
					}
				},
				"lastMsg" : ["STATUS", "Hi Mario! I'm your Technogym Cognitive Trainer and we will travel together along the path to your physical well-being!", "Listen , before getting started, I need to ask you a set of questions to better undestand you and provide you a personalized training experience. Ready to start?"],
				"trainingContext" : {
					"status" : "no_tp"
				},
				"userContext" : {
					"userID" : "fdd6e44258cc44c5a85a322dedae68bf",
					"firstName" : "Mario",
					"lastName" : "Rossi",
					"userToken" : "MjAxNzA1MTExNzA1NTB8OWUzYmQ0OGNkZDRmNDc0ZTg2OTEyYWVmMDUwODZlYWJ8ZWMxZDM4ZDdkMzU5NDhkMGE2MGNkOGMwYjhmYjlkZjl8MnxSb21hbmNlIFN0YW5kYXJkIFRpbWV8ZW4tR0J8ZmRkNmU0NDI1OGNjNDRjNWE4NWEzMjJkZWRhZTY4YmZ8fHx8MXwxfDB8MXx8fDQyfDl8MHxjb20ubXl3ZWxsbmVzcw2.97B516D656DD4A782E017001DB6DCCA931A3ED48",
					"facilityId" : "04f1acd1-374b-46e9-af4f-b7f562b806d6",
					"height" : 160,
					"dob" : "26/10/1989"
				},
				"aspFinder" : {},
				"action_ui" : "weight"
			},
			"alternate_intents" : true
		}
	}
}'

- The index is named technogym

I'm trying to manage the array in the pattern doc.APIresponse.intents at this moment.

Sorry but I'm very interested in this plugin and I would like to make it working.

Thanks.

**Comment by andrewkcarter** [comment]
Try
```
{
    "index_pattern":{
        "technogym":{
            "include":[
                "doc.APIresponse.intents"
            ]
        }
    }
}
```

**Comment by andrewkcarter** [comment]
When you look at the fields list for you index pattern, you probably see listed:
```
doc.APIresponse.intents.intent
doc.APIresponse.intents.confidence
```
and what you're trying to add is the parent of those two fields, i.e:
```
doc.APIresponse.intents
```

**Comment by filippoleoncini** [comment]
Thank you very much, your solution works.

Another question (the last one ;) ).

I have this field now:

![immagine](https://cloud.githubusercontent.com/assets/20639905/26207568/321cb238-3be8-11e7-89a7-578ba1139366.png)

Can I use this new field to make an histogram that shows me the "confidence" per "intent"? Because it is this my goal.

Thanks for your professional answer and kindness ;)

**Comment by andrewkcarter** [comment]
@filippoleoncini Glad to help. As far as your histogram visualization, you should be able to accomplish that without the need for this plugin or the configuration you just did. This plugin specifically gives you the ability to apply a display format to fields that Kibana leaves as JSON in the search table.

For your histogram, create a new vertical bar chart, and select a Y-axis aggregation other than count (such as avg, sum, etc.) and for the field select `doc.APIresponse.intents.confidence`. Then for the X-axis chose a Terms aggregation and for the field select `doc.APIresponse.intents.intent`.
