### ISSUE TITLE
GIVE LINK TO DOWNLOAD THIS PLUGIN FROM

### ISSUE THREAD

**Issue by anandgavai** [istresearch/kibana-object-format#23]

**Comment by andrewkcarter** [comment]
Calm down my friend! https://github.com/istresearch/kibana-object-format/releases

![screen shot 2018-04-11 at 12 47 44 pm](https://user-images.githubusercontent.com/7338230/38631126-dc7773ee-3d86-11e8-85c7-c23b807c3f78.png)

Match up your Kibana version with the last part of the asset filename.

**Comment by anandgavai** [comment]
Just following git recommendations ;-) nothing personal !

I could figure it out, my group members kept asking me about it !

thanks !

**Comment by andrewkcarter** [comment]
You're welcome. I hope the plugin works well for you.
