### ISSUE TITLE
Error loading index - fieldMapperHack:fields

### ISSUE THREAD

**Issue by hjotha** [istresearch/kibana-object-format#24]
After installing the plugin I am receiving the following error when loading an index in kibana:

Unexpected config.get("fieldMapperHack:fields") call on unrecognized configuration setting "fieldMapperHack:fields". Setting an initial value via config.set("fieldMapperHack:fields", value) before attempting to retrieve any custom setting value for "fieldMapperHack:fields" may fix this issue. You can also save an step using config.get("fieldMapperHack:fields", defaultValue), which will set the initial value if one is not already set.

less
Less Info
OK
Error: Unexpected `config.get("fieldMapperHack:fields")` call on unrecognized configuration setting "fieldMapperHack:fields".
Setting an initial value via `config.set("fieldMapperHack:fields", value)` before attempting to retrieve
any custom setting value for "fieldMapperHack:fields" may fix this issue.
You can also save an step using `config.get("fieldMapperHack:fields", defaultValue)`, which
will set the initial value if one is not already set.
    at getCurrentValue (http://kibpx03:8080/bundles/commons.bundle.js?v=16602:1:497342)
    at Object.config.get (http://kibpx03:8080/bundles/commons.bundle.js?v=16602:1:498409)
    at http://kibpx03:8080/bundles/commons.bundle.js?v=16602:1:183607
    at processQueue (http://kibpx03:8080/bundles/vendors.bundle.js?v=16602:58:132456)
    at http://kibpx03:8080/bundles/vendors.bundle.js?v=16602:58:133349
    at Scope.$digest (http://kibpx03:8080/bundles/vendors.bundle.js?v=16602:58:144239)
    at Scope.$apply (http://kibpx03:8080/bundles/vendors.bundle.js?v=16602:58:147018)
    at done (http://kibpx03:8080/bundles/vendors.bundle.js?v=16602:58:100026)
    at completeRequest (http://kibpx03:8080/bundles/vendors.bundle.js?v=16602:58:104697)
    at XMLHttpRequest.xhr.onload (http://kibpx03:8080/bundles/vendors.bundle.js?v=16602:58:105435)

Dunno how to fix.

**Comment by andrewkcarter** [comment]
Which specific version did you install and what version of Kibana are you running?

**Comment by hjotha** [comment]
Version: 6.2.3
Plugin: 6.2.3

**Comment by andrewkcarter** [comment]
Interesting. Kibana should be loading a default value from the package.json file. If you go to _Management -> Advanced Settings_ is the configuration present in the table and filled with the default value?

**Comment by hjotha** [comment]
Yes, when I click the index for kibana to show it the error happens and the index does not get loaded.

![image](https://user-images.githubusercontent.com/23729943/38750051-1313da9c-3f2a-11e8-87c8-3bf652e798e2.png)

**Comment by andrewkcarter** [comment]
Would you be able to pull and build #25 locally to test it? If not, I'll try and get to it over the weekend.

The instructions for building are here: https://github.com/istresearch/kibana-object-format#development

**Comment by hjotha** [comment]
Management -> Advanced Settings
![image](https://user-images.githubusercontent.com/23729943/38750225-a3bf0dbe-3f2a-11e8-8d8b-baea81b4e874.png)

**Comment by Xosmond** [comment]
could you please make a "release" link to try that ? I have tried modify the file and then compressing  the zip but got this:

`Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"`

**Comment by andrewkcarter** [comment]
@Xosmond are you experiencing the same error? If so, what is your Kibana version?

**Comment by Xosmond** [comment]
All ELK stack are on 6.2.3

**Comment by andrewkcarter** [comment]
Interesting. I'm not able to reproduce this using the ES 6.2.3 docker image.
Here is a build to try: https://github.com/istresearch/kibana-object-format/releases/download/v0.1.3/kibana_object_format-0.1.3-kbn_6.2.3-564c1b2.zip

**Comment by Xosmond** [comment]
I will take a look tomorrow Andrew! Here is too late

**Comment by Xosmond** [comment]
I got the plugin installed with no error message! but looks like it doesn't work, the field doesn't appear on the index field list after update fields.

**Comment by andrewkcarter** [comment]
A common mistake is to use the display name instead of the ID of the index pattern when defining the field mapper hack. Could this be why it's not registering your field when you refresh?

**Comment by Xosmond** [comment]
I dont think so, maybe because the objects inside the array has internal objects (and some have different data)?

Like 
```json
[
  {
    "hello": "assay",
    "data": {
      "id": "12312",
      "asd": "asd"
    }
  },
  {
    "hello": "assay",
    "data": {
      "id": "12312",
      "asd": "asd"
    }
  },
  {
    "hello": "assay",
    "data": {
      "limn": "afafqw",
      "posakpns": "1234"
    }
  }
]
```

I have that kind of data 😕
