### ISSUE TITLE
kibana v6.3.2

### ISSUE THREAD

**Issue by aaratushnyak** [istresearch/kibana-object-format#29]
** Environment **
 - OS: aws linux
 - Kibana version 6.3.2

**Describe the bug**
we are use kibana and ES v6.3.2. where can I download kibana-object-format for it version

[root@dev-logstash ~]# rpm -qa|grep kibana
kibana-6.3.2-1.x86_64
[root@dev-logstash ~]# rpm -qa|grep elasticsearch
elasticsearch-6.3.2-1.noarch

**Comment by pettersoderlund** [comment]
6.3.2 doesnt seem to be released. https://github.com/istresearch/kibana-object-format/releases/tag/v0.1.6
Either you can try building it yourself or wait for @andrewkcarter to release it :)

**Comment by aaratushnyak** [comment]
@andrewkcarter when are you release for 6.3.2?

**Comment by andrewkcarter** [comment]
Here you go: https://github.com/istresearch/kibana-object-format/releases/tag/v0.1.6

**Comment by aaratushnyak** [comment]
thanks
