### ISSUE TITLE
Nested Json example

### ISSUE THREAD

**Issue by adistoica** [istresearch/kibana-object-format#3]
Hi!

I recently gave your plugin a try, however I think I'm having a configuration issue on my end.

Could you please paste the exact nested JSON example you are using in the README.md gif file?

<img width="662" alt="screen shot 2017-05-23 at 10 02 12 pm" src="https://cloud.githubusercontent.com/assets/8807531/26371491/96f2fdce-4003-11e7-8dba-605662881f59.png">

I would like to compare it to my current setup, to make sure everything is okay.

Many thanks,
Adrian

**Comment by madisonb** [comment]
I think this is what you are looking for:

```
{
  "attribs": {
    "type": "Emoji"
  },
  "results": [
    {
      "description": "unamused face",
      "value": "😒"
    },
    {
      "description": "oncoming fist",
      "value": "👊"
    }
  ]
}
```

This is a random example but that should still give you the idea.

**Comment by adistoica** [comment]
Thank you @madisonb ! I've managed to correctly configure the plugin, based on the sample you provided!
