### ISSUE TITLE
Error retrieving metadata from plugin archive

### ISSUE THREAD

**Issue by genesisyau** [istresearch/kibana-object-format#30]
I'm getting this message every time I try to install the plugin:

Attempting to transfer from https://github.com/istresearch/kibana-object-format/archive/v0.1.6_kbn-6.3.2.tar.gz
Transferring unknown number of bytes
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

I've tried with these links
https://github.com/istresearch/kibana-object-format/archive/v0.1.6_kbn-6.3.2.tar.gz
https://github.com/istresearch/kibana-object-format/releases/download/v0.1.6/kibana_object_format-0.1.6-kbn_6.3.2.zip
https://github.com/istresearch/kibana-object-format/archive/v0.1.6.tar.gz

But I always get the same error message.

I'm using kibana 6.3.2 and the OS is Ubuntu 16

**Comment by andrewkcarter** [comment]
https://github.com/istresearch/kibana-object-format/releases/download/v0.1.6/kibana_object_format-0.1.6-kbn_6.3.2.zip
Is the correct URL.

**Comment by genesisyau** [comment]
I've successfullydownloaded the plugin, but the index fieldMapperHack:fields in advanced settings won't appear.
![error](https://user-images.githubusercontent.com/26565579/44638509-cc02a680-a9e9-11e8-812e-a76f93b61243.JPG)
