### ISSUE TITLE
cannot see the new property in kibana 6.2.2 

### ISSUE THREAD

**Issue by arielrolfo** [istresearch/kibana-object-format#32]
I've managed to install the plugin with the provided instructions but still cannot see the new property the plugin is supposed to add in the Advanced Settings table according with Instructions step#2

**Comment by arielrolfo** [comment]
`kibana.stdout:{"type":"log","@timestamp":"2018-10-01T19:13:21Z","tags":["plugin","warning"],"pid":68047,"path":"/usr/share/kibana/plugins/kibana_object_format","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/kibana_object_format"}
kibana.stdout:{"type":"log","@timestamp":"2018-10-01T19:16:39Z","tags":["plugin","warning"],"pid":70146,"path":"/usr/share/kibana/plugins/kibana_object_format","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/kibana_object_format"}
kibana.stdout:{"type":"log","@timestamp":"2018-10-01T19:24:54Z","tags":["status","plugin:kibana@6.2.2","info"],"pid":70146,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana.stdout:{"type":"log","@timestamp":"2018-10-01T19:24:54Z","tags":["status","plugin:elasticsearch@6.2.2","info"],"pid":70146,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana.stdout:{"type":"log","@timestamp":"2018-10-01T19:24:54Z","tags":["status","plugin:console@6.2.2","info"],"pid":70146,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana.stdout:{"type":"log","@timestamp":"2018-10-01T19:24:54Z","tags":["status","plugin:metrics@6.2.2","info"],"pid":70146,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana.stdout:{"type":"log","@timestamp":"2018-10-01T19:24:55Z","tags":["status","plugin:timelion@6.2.2","info"],"pid":70146,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana.stdout:{"type":"log","@timestamp":"2018-10-01T19:24:55Z","tags":["status","plugin:elasticsearch@6.2.2","info"],"pid":70146,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}`

**Comment by andrewkcarter** [comment]
```
Skipping non-plugin directory at /usr/share/kibana/plugins/kibana_object_format
```
@arielrolfo try removing that directory and re-installing the plugin. Perhaps it's borked from an earlier attempt or a failed download.

**Comment by arielrolfo** [comment]
I've tried removing it and re-installing the plugin and still facing that msg when I restart kibana ```{"type":"log","@timestamp":"2018-10-02T02:54:45Z","tags":["plugin","warning"],"pid":51063,"path":"/usr/share/kibana/plugins/kibana_object_format","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/kibana_object_format"}```

**Comment by andrewkcarter** [comment]
These are the logs I get when installing the plugin. Please compare to yours.
```
kibana [(HEAD detached at v6.2.2)] $ ./bin/kibana-plugin install https://github.com/istresearch/kibana-object-format/releases/download/v0.1.6/kibana_object_format-0.1.6-kbn_6.2.2.zip
Attempting to transfer from https://github.com/istresearch/kibana-object-format/releases/download/v0.1.6/kibana_object_format-0.1.6-kbn_6.2.2.zip
Transferring 14979 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
kibana [(HEAD detached at v6.2.2)] $ ls -l plugins/kibana_object_format/
total 24
-rw-r--r--  1 ****  staff  976 Oct  2 11:31 index.js
drwxr-xr-x  2 ****  staff   64 Oct  2 11:31 node_modules
-rw-r--r--  1 ****  staff  490 Oct  2 11:31 package.json
drwxr-xr-x  5 ****  staff  160 Oct  2 11:31 public
-rw-r--r--  1 ****  staff   86 Oct  2 11:31 yarn.lock
```
And then when starting Kibana:
```
  log   [15:35:08.919] [info][listening] basePath Proxy running at http://localhost:5601/zny
server    log   [15:35:13.650] [info][optimize] Waiting for optimizer to be ready
optmzr    log   [15:35:13.814] [info][optimize] Optimization started
optmzr    log   [15:35:13.849] [info] Plugin initialization disabled.
server    log   [15:35:13.916] [info][status][plugin:kibana@6.2.2] Status changed from uninitialized to green - Ready
server    log   [15:35:14.025] [info][status][plugin:elasticsearch@6.2.2] Status changed from uninitialized to yellow - Waiting for Elasticsearch
server    log   [15:35:16.449] [info][status][plugin:timelion@6.2.2] Status changed from uninitialized to green - Ready
server    log   [15:35:16.462] [info][status][plugin:console@6.2.2] Status changed from uninitialized to green - Ready
server    log   [15:35:16.468] [info][status][plugin:metrics@6.2.2] Status changed from uninitialized to green - Ready
server    log   [15:35:16.492] [info][listening] Server running at http://localhost:5603
server    log   [15:35:16.525] [info][status][plugin:elasticsearch@6.2.2] Status changed from yellow to green - Ready
optmzr    log   [15:36:17.398] [info][optimize] Optimization success in 63.58 seconds
optmzr    log   [15:36:20.266] [info][optimize] Optimization success in 1.78 seconds
```
![screen shot 2018-10-02 at 11 37 28 am](https://user-images.githubusercontent.com/7338230/46359795-fa525200-c637-11e8-842c-add959334efa.png)

I seems to me that something is failing on your end during the download.
