### ISSUE TITLE
Unable to install this plugin 

### ISSUE THREAD

**Issue by HariKRrishnan** [istresearch/kibana-object-format#36]
Plugin installation was unsuccessful due to error "Plugin kibana_object_format [6.3.2] is incompatible with Kibana [6.6.1]"
Plugin installation was unsuccessful due to error "Plugin kibana_object_format [6.3.1] is incompatible with Kibana [6.6.1]"
Plugin installation was unsuccessful due to error "Plugin kibana_object_format [6.2.4] is incompatible with Kibana [6.6.1]"
Plugin installation was unsuccessful due to error "Plugin kibana_object_format [6.3.0] is incompatible with Kibana [6.6.1]"

**Comment by WeslyG** [comment]
you need to open zip and edit package.json on your current kibana version, and try install again.

**Comment by andrewkcarter** [comment]
I expect some incompatibilities with Kibana 6.4+. I just haven't had time to address them.
