### ISSUE TITLE
Why cann't I add a field?

### ISSUE THREAD

**Issue by JaffaSha** [istresearch/kibana-object-format#38]
** Environment **
 - Kibana version [e.g. 6.3.2]
 - Kibana Object Formatter plugin version [e.g. 0.1.6_kbn-6.3.2]

**Describe the bug**
I edited the "fieldMapperHack:fields". I did exactly like the example of the "my_index":{
         "include":[
            "book"
         ]  etc
But in the index pattern, no field added. (I tried to refresh the fields).

Why?

**Comment by andrewkcarter** [comment]
Hi @jaffasha. The first thing I would look at is the ID of your index pattern, and ensure it matches the key value in the `fieldMapperHack:fields`. Kibana will issue a UUID as the underlying ID which is different than the display name you gave it, unless you explicitly set the ID during index pattern creation.

**Comment by JaffaSha** [comment]
Yes, It works!
Thank you!

**Comment by fstefanov** [comment]
Oddly I'm having the same issue same Kibana version 6.3.2
Formatter plugin version 0.1.6_kbn-6.3.2

**fieldMapperHack:fields**

```
{
   "index_pattern":{
      "*":{
         "include":[

         ],
         "exclude":[
            ".*"
         ]
      },
      "Zhxjl6GaToKAPrtNxpGv8A":{
         "include":[
            "book"
         ]
      }
   }
}
```
My test index:
```
{
  "_index": "nest",
  "_type": "doc",
  "_id": "999",
  "_version": 1,
  "_score": 0,
  "_source": {
    "book": {
      "author": "John Jenkins",
      "title": "Building Code"
    }
  }
}
```
Some of my index settings:
```
{
  "settings": {
    "index": {
      "creation_date": "1567102121843",
      "number_of_shards": "5",
      "number_of_replicas": "1",
      "uuid": "Zhxjl6GaToKAPrtNxpGv8A",
      "version": {
        "created": "6030299"
      },
      "provided_name": "nest"
    }
  },
```
Index mapping:
```
{
  "mapping": {
    "doc": {
      "properties": {
        "book": {
          "properties": {
            "author": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "title": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        }
      }
    }
  }
}
```
Reflesh field list does not add expected book field
```
_id                 string
_index              string
_score              number
_source             _source
_type               string	
book.author         string
book.author.keyword string
book.title          string
book.title.keyword  string
```
And there is no JSON object book in the Discover tab
 t book.author
 t book.title

**Comment by andrewkcarter** [comment]
@fstefanov, it appears that you are referencing the UID of the index instead of the index pattern in your fieldMapperHack:fields JSON.

One way to get the index pattern ID is to select the index pattern in Kibana -> Management -> Index Patterns and then pull the value from the URL. Another more involved approach is querying the .kibana index for the information:
```
GET .kibana/_search
{
  "query": {
    "query_string": {
      "query": "type:index-pattern"
    }
  },
  "_source": ["_id", "index-pattern.title"]
}
``` 
should give you...
```
      {
        "_index": "nest,
        "_type": "doc",
        "_id": "index-pattern:6f0f8ad0-36b9-11e9-b0dd-191de2ceeb2b",
        "_score": 2.2794626,
        "_source": {
          "index-pattern": {
            "title": "nest-*"
          }
        }
      },
```
Then take and use the UID that is part of the `_id` field for the index pattern you are targeting. In this example:
```
{
   "index_pattern":{
...
      "6f0f8ad0-36b9-11e9-b0dd-191de2ceeb2b":{
         "include":[
            "book"
         ]
      }
...
}
```

**Comment by maxisam** [comment]
IMHO, this should be in the readme.
