### ISSUE TITLE
Array of Objects not visible on Index Patterns

### ISSUE THREAD

**Issue by sidharthchugh** [istresearch/kibana-object-format#4]
I have installed the plugin but If you check attached screenshots, partnerDetailSearch array is not visible on Index Patterns.

![screen shot 2017-05-27 at 00 09 38](https://cloud.githubusercontent.com/assets/1497853/26514265/0e49cbe0-4271-11e7-8718-46af6e2f2af1.png)
![screen shot 2017-05-27 at 00 09 10](https://cloud.githubusercontent.com/assets/1497853/26514269/13dc0532-4271-11e7-8d3c-5832191722a4.png)

**Comment by madisonb** [comment]
@sidharthchugh Can you provide your exact kibana version, a small sample doc, and the current settings for `fieldMapperHack:fields` so we may better try to reproduce the issue? 

Did you refresh the index mappings after installing the plugin and configuring the above?

**Comment by sidharthchugh** [comment]
@madisonb  

Kibana Version : 5.4.0
fieldMapperHack:fields = {"index_pattern":{"*":{"include":[],"exclude":[".*"]}}}

sample data:

partnerDetailSearch:  {
  "meta": {
    "name": "partnerDetailSearch",
    "type": "Strategic partners - Do not take into account my company profile",
    "createdAt": 1495723800297,
    "searchStatus": "searchDeleted",
    "matchLoaded": "true"
  },
  "fields": {
    "partnerDetailSearchName": {
      "type": "string",
      "typeValues": "adasd"
    },
    "partnerBusinessObjective": {
      "type": "dropdownMultiple",
      "typeValues": []
    },
    "partnerIndustry": {
      "type": "dropdownMultiple",
      "typeValues": []
    },
    "partnerSector": {
      "type": "dropdownMultiple",
      "typeValues": []
    },
    "partnerSubSector": {
      "type": "dropdownMultiple",
      "typeValues": []
    },
    "partnerOrganizationType": {
      "type": "dropdownMultiple",
      "typeValues": []
    },
    "partnerBusinessType": {
      "type": "dropdownMultiple",
      "typeValues": []
    },
    "partnerKeyActivities": {
      "type": "multiSelectAutoSuggest",
      "typeValues": []
    },
    "partnerKeyResources": {
      "type": "multiSelectAutoSuggest",
      "typeValues": []
    },
    "partnerChannel": {
      "type": "multiSelectAutoSuggest",
      "typeValues": []
    },
    "partnerLocation": {
      "type": "multiSelect",
      "typeValues": []
    },
    "partnerLanguages": {
      "type": "multiSelectAutoSuggest",
      "typeValues": []
    },
    "partnerTechnologyField": {
      "type": "dropdownMultiple",
      "typeValues": []
    },
    "partnerProductClass": {
      "type": "dropdownMultiple",
      "typeValues": [
        {
          "_id": "5926ef18bb432fd8357796e6",
          "className": "",
          "value": "Software",
          "label": "Software"
        },
        {
          "_id": "5926ef18bb432fd8357796e5",
          "className": "",
          "value": "Service (Consulting, Design, Marketing, ...)",
          "label": "Service (Consulting, Design, Marketing, ...)"
        }
      ]
    },
    "partnerProductCategory": {
      "type": "multiSelect",
      "typeValues": []
    },
    "partnerDigitalizationScopeMin": {
      "type": "dropdown",
      "typeValues": ""
    },
    "partnerFtes": {
      "type": "dropdownMultiple",
      "typeValues": []
    },
    "partnerCapacityIndication": {
      "type": "multiSelect",
      "typeValues": []
    },
    "partnerStandardsCertifications": {
      "type": "multiSelect",
      "typeValues": []
    },
    "partnerTechnologies": {
      "type": "multiSelect",
      "typeValues": []
    },
    "partnerLegalConsideration": {
      "type": "textArea",
      "typeValues": ""
    },
    "partnerOtherPartnerCharacteristics": {
      "type": "multiSelect",
      "typeValues": []
    }
  },
  "matches": []
}


Yes, I refreshed the index mappings after installing plugin.

I have also tried with Kibana version 5.3.0, but it didn't work

I really appreciate your help in this regard.

**Comment by andrewkcarter** [comment]
@sidharthchugh Try this configuration for fieldMapperHack:fields:
```
{"index_pattern":{"*":{"include":["partnerDetailSearch"],"exclude":[]}}}
```

**Comment by sidharthchugh** [comment]
@andrewkcarter Thank you for your reply, Now I can see partnerDetailSearch in index pattern, can you also please suggest me what i have to write in index pattern.

I am unable to see proper result on discover of kibana. I tried but did'nt work :(

<img width="1495" alt="screen shot 2017-05-30 at 17 23 47" src="https://cloud.githubusercontent.com/assets/1497853/26591277/6fd5e008-455d-11e7-87b4-8c85984c6f0c.png">

**Comment by andrewkcarter** [comment]
Depending on what you want to see, you would then fill in the `label` and `field` for each:
_field:_ `meta.type`
or maybe
_label_: `Search Name` and _field_: `fields.partnerDetailSearchName.typeValues`
**Add Field**
_label_: `Technologies` and _field_: `fields.partnerTechnologyField.typeValues`

**Comment by sidharthchugh** [comment]
Awesome, you are really great. Made by Day. Thanks :)
