### ISSUE TITLE
kibana v6.4.0

### ISSUE THREAD

**Issue by maxisam** [istresearch/kibana-object-format#40]
** Environment **
 - OS: windows
 - Browser firefox
 - Kibana version 6.4.0
 - Kibana Object Formatter plugin version 0.1.6

**Describe the bug**
I changed the package number to 6.4.0 and it doesn't work. 

When I tried to assign the format type object to the field, it threw a message like 

Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. (https://celk.millerslab.com/bundles/vendors.bundle.js:213)

Version: 6.4.0
Build: 17929

Error: Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. (https://celk.millerslab.com/bundles/vendors.bundle.js:213)
window.onerror@https://celk.millerslab.com/bundles/commons.bundle.js:3:769367

The error from https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=object&args[]=
"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object."

I know it is not supported in 6.4.0 but I am still wondering if there is a way to make it work

**Comment by andrewkcarter** [comment]
This is going to be a lot of work. The Kibana team has been methodically replacing Angular with React, and 6.4 is where this broke the plugin. Honestly, I'm not going to ever get this supported on 6.4 directly. If I pick this up again, I will be starting with Kibana 7.4 support or later. From there, I may be able to back port it, but I can't promise anything.

**Comment by maxisam** [comment]
I see. 7.4 is fine with me too. I can upgrade to it. I wonder if I can use 6.3 with elasticsearch 6.4. I feel like it should be fine, but I don't have lots of experience with elk.

**Comment by andrewkcarter** [comment]
Kibana and Elasticsearch (and the other applications) are supposed to be in major and minor version lockstep. Kibana 6.3 might start against Elasticsearch 6.4, but it will be logging warnings on startup.

**Comment by maxisam** [comment]
@andrewkcarter  thanks!

**Comment by andrewkcarter** [comment]
We've jumped to Kibana 7.6.2. No plans to backport.
