### ISSUE TITLE
Field mapping don't work

### ISSUE THREAD

**Issue by enz0slyde** [istresearch/kibana-object-format#5]
Hello, 

I am trying your plugin with your examples and many other samples but the field mapping never success..

This is the index I got with your second example (in the README) : 
![image](https://user-images.githubusercontent.com/29545747/27289573-b2a68510-550a-11e7-9ff8-755da221b3cb.png)

Using your fieldMapperHack :
![image](https://user-images.githubusercontent.com/29545747/27289768-6ba50d70-550b-11e7-9081-b71ee30274a9.png)

And that's what I got in Discover :
![image](https://user-images.githubusercontent.com/29545747/27289839-a8cbe5f2-550b-11e7-8ab7-daa655ee7420.png)

I refreshed the index pattern many times.
I don't understand why it's not working, please help :/

**Comment by madisonb** [comment]
Your kibana index pattern shows the entry as `my_index*` but the pattern you have in the plugin is only `my_index` (no `*`). Do you have an alias set up and will Elasticsearch consider `my_index` as a valid index? If you use use `my_index*` in the fieldMapperHack:fields entry what are your results?

**Comment by enz0slyde** [comment]
Ok I just found a [closed issue who gave me the answer.](https://github.com/istresearch/kibana-object-format/issues/4)

I must use a fieldMapperHack like this : 
{"index_pattern":{"*":{"include":["new_releases"],"exclude":[]}}}

**Comment by enz0slyde** [comment]
Hello madisonb,

You are right !
Using this filedMapperHack work !
{
    "index_pattern":{
        "*":{
            "include":[

            ],
            "exclude":[
                ".*"
            ]
        },
        "my_index*":{
            "include":[
                "new_releases"
            ]
        }
    }
}

Thank you !
