### ISSUE TITLE
Kibana 5.5

### ISSUE THREAD

**Issue by andyh69uk** [istresearch/kibana-object-format#6]
Hi love the plugin, have you started working on a 5.5 release yet?

**Comment by andrewkcarter** [comment]
It's in the works. There are a few changes under the hood of 5.5 we need to account for.

**Comment by elvarb** [comment]
Any updates?

**Comment by andrewkcarter** [comment]
Almost there. 
https://github.com/istresearch/kibana-object-format/pull/7

**Comment by zwayne** [comment]
Is 5.5.2 supported? I can't seem to get it installed.

> ○ → bin/kibana-plugin install istresearch/kibana_object_format
> Attempting to transfer from istresearch/kibana_object_format
> Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/istresearch/kibana_object_format/istresearch/kibana_object_format-5.5.2.zip
> Plugin installation was unsuccessful due to error "No valid url specified."

**Comment by andrewkcarter** [comment]
@zwayne You can see the packaged release versions here: https://github.com/istresearch/kibana-object-format/releases. These are the only ones I have tested and know are compatible.

If you don't see one for your version, you can build your own from master (or the closest tag to your older version). Just follow the instructions for building found here: https://github.com/istresearch/kibana-object-format#development

You'll need to edit the version in this file to match your Kibana or it won't load: https://github.com/istresearch/kibana-object-format/blob/0fe41f5816bf695387ff2f285e9ae298b3e75f4d/package.json#L8

**Comment by mcezzare** [comment]
Hy just to share. I was able to fork the project and just changed the package.json to 5.6.3
"kibana": {
    "version": "5.6.3"
  },

and in the machine i used to build , on the directory build, just run a python command to serve the file: 
```
[mcezzare@N-CATHO-013164 build]$ python -m http.server 
```
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
10.80.61.99 - - [23/Nov/2017 20:28:03] "GET /kibana_object_format-0.1.1.zip HTTP/1.1" 200 -

and on the machine running kibana typed:
```
mcezzare@vm-tmb-devtools01:/opt/kibana$ ./bin/kibana-plugin install http://172.16.19.189:8000/kibana_object_format-0.1.1.zip
```
Attempting to transfer from http://172.16.19.189:8000/kibana_object_format-0.1.1.zip
Transferring 12049 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete

**Comment by mcezzare** [comment]
if you can't run build, I left a version at: https://github.com/mcezzare/kibana-object-format/blob/master/kibana_object_format-0.1.1.zip

**Comment by tschroeder-zendesk** [comment]
Are you going to do a release for 5.5.x and 5.6.x anytime soon? It seem the code is there already just no release is done.

**Comment by andrewkcarter** [comment]
https://github.com/istresearch/kibana-object-format/releases/tag/v0.1.1_kbn_5.5.3
https://github.com/istresearch/kibana-object-format/releases/tag/v0.1.2_kbn_5.6.7
Release packages on the way.
