### ISSUE TITLE
Kibana 7.9 Support

### ISSUE THREAD

**Issue by godfried** [istresearch/kibana-object-format#65]
Hi,

Do you have an plans for creating a release supporting Kibana 7.9?
Thanks for your work.

**Comment by andrewkcarter** [comment]
Very likely, although I don't have a schedule for that. You can try repackaging it for 7.9. I do not know if it requires any code changes yet. The plugin build script will prompt you for the Kibana version to target. If you do try it, and you encounter an issue please report it back here.
