### ISSUE TITLE
Problems with installing this plug-in in kibana7.9.3

### ISSUE THREAD

**Issue by chentiannan** [istresearch/kibana-object-format#68]
** Environment **
 - OS:centos7
 - Kibana version [e.g. 7.9.3]
 - Kibana Object Formatter plugin version [master]

**Describe the bug**
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by andrewaxelrod-ist** [comment]
We are in the process of upgrading the plugin for the newer versions of Kibana.   This plugin should be ready within the next month.

**Comment by mickvv** [comment]
Dear @andrewaxelrod-ist , 
Do you have any news about the plugin ?
Thank you

**Comment by andrewkcarter** [comment]
Starting with Kibana 7.12, the multi-fields and list of objects are now displayed and filterable by Kibana itself without the use if this plugin. Development of this project has ceased and we will not be maintaining it going forward.
