### ISSUE TITLE
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

### ISSUE THREAD

**Issue by dajs3010** [istresearch/kibana-object-format#9]
Hi, I'm trying to install this plug in, but I'm getting the following error:

Transferring 2077938 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

I have tried installing from URL and from the downloaded file with no success:

bin/kibana-plugin install file:///Users/mono/elastic_local/kibana-object-format-master.zip
bin/kibana-plugin install https://github.com/istresearch/kibana-object-format/archive/master.zip

bin/kibana-plugin install file:///Users/mono/elastic_local/kibana-object-format-master.zip -d /Users/mono/elastic_local/kibana-5.6.0-darwin-x86_64/plugins/
bin/kibana-plugin install https://github.com/istresearch/kibana-object-format/archive/master.zip -d /Users/mono/elastic_local/kibana-5.6.0-darwin-x86_64/plugins/

Please Help, I'm using Kibana 5.6

**Comment by andrewkcarter** [comment]
HI. You need to use the URLs for the releases found here: https://github.com/istresearch/kibana-object-format/releases

I haven't made a release for 5.6 yet, but the changes are about ready. In the meantime, you could checkout the master branch and follow the instructions here (https://github.com/istresearch/kibana-object-format#development) to build the source into the plugin package which you can install into Kibana 5.6. Or you can wait for me to make a 5.6 release, which should be in a week or two.

**Comment by dajs3010** [comment]
Hi thanks for helping me, I already set the environment and run successfully the build command but I can't find the plugin installation file... where is it? Should I put the plugin zip or the folder int the plugins folder? Or what I'm doing wrong?
